### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Botami143** [utkusen/socialhunter#3]
Hello 

This tool not working 

My single Website working 

But list of website not working

My systam windows 10

Tool Error :

PS C:\Users> socialhunter -f url.txt

         Utku Sen's
        \ \     / /
         \ \   / /
          \ \_/ /
           \   /
        socialhunter
           / _ \
          / / \ \
         / /   \ \
        /_/     \_\
        utkusen.com

Total URLs: 2
Checking: https://j69o12wenlqcbt2za2l0cw.on.drv.tw/d.html
Checking: https://j69o12wenlqcbt2za2l0cw.on.drv.tw/frg.html
panic: parse "https://j69o12wenlqcbt2za2l0cw.on.drv.tw/frg.html\r": net/url: invalid control character in URL

goroutine 7 [running]:
main.visitor({0xc00004a0e0, 0x32}, 0xa)
        C:/Users/USER/go/pkg/mod/github.com/utkusen/socialhunter@v0.1.1/main.go:230 +0x2f9
main.action({0xc00004a0e0, 0x32})
        C:/Users/USER/go/pkg/mod/github.com/utkusen/socialhunter@v0.1.1/main.go:68 +0x45
main.main.func1()
        C:/Users/USER/go/pkg/mod/github.com/utkusen/socialhunter@v0.1.1/main.go:58 +0x94
github.com/gammazero/workerpool.startWorker(0x0?, 0xc00005a0c0)
        C:/Users/USER/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:233 +0x22
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        C:/Users/USER/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:195 +0x25c

**Comment by sharingeconomypakistan** [comment]
Invalid control character...
create file windows.go and copy paste following block of code into it

// +build windows
package main
const EndOfLine = "\r\n"
